### ISSUE TITLE
Special characters are escaped in entitygraphql

### ISSUE THREAD

**Issue by santhidhanuskodi23** [EntityGraphQL/EntityGraphQL#399] opened 2024-08-28 12:23 UTC
Hi,
GraphQL output is showing single quotes as \u00275, for eg "Ravi's test" is shown as "Ravi\u00275s test"....how will I preserve single quotes as it is....

**Comment by santhidhanuskodi23** [comment] 2024-08-30 12:03
Could someone please respond for this

**Comment by bzbetty** [comment] 2024-08-30 23:09
Hey Santhid, could you make a small project or unit test to repro this issue?

**Comment by lukemurray** [comment] 2024-09-02 04:59
Yes, something to reproduce would be helpful. More information about all the other pieces you are using as well. This library doesn't change strings (unless they need to be converted to dates etc) - the data you are loading may, or the JSON serialisation may.

**Comment by lukemurray** [comment] 2024-09-02 07:20
Where does the data come from and what is the string format of that (UTF8, UTF16, etc)?

**Comment by santhidhanuskodi23** [comment] 2024-09-02 07:24
The data comes from on-prem SQL server tables. Will sql tables specify the string format? I dont think so...

**Comment by lukemurray** [comment] 2024-09-02 07:35
Also turns out the `RuntimeTypeJsonConverter` is incorrectly not serialising `null` fields. As the spec does state to return `null`. Will fix this.

**Comment by santhidhanuskodi23** [comment] 2024-09-02 07:38
Thanks lukemurray!.... What about special characters being escaped?

**Comment by lukemurray** [comment] 2024-09-03 02:10
`'` to `\u0027` seems to be the default for `JavaScriptEncoder.Default`.

The fix pushed for the `null`s should also fix `opts.JsonSerializerOptions.Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping;` not being used.

**Comment by santhidhanuskodi23** [comment] 2024-09-03 05:50
What should be added in my code to retrieve this fix? Should I add a separate controller? Wat changes are needed in startup.cs?

**Comment by lukemurray** [comment] 2024-09-03 07:05
reference the new version from nuget is the normal way, version `5.4.3`. Unless you are including the code directly then you need to update the repo you have checked out.

**Comment by lukemurray** [comment] 2024-09-12 05:19
Fixed in 5.4.3

**Closed by lukemurray** 2024-09-12 05:19 UTC
