### ISSUE TITLE
Use OutputCache with Entity GraphQl?

### ISSUE THREAD

**Issue by PhilippeWaeber** [EntityGraphQL/EntityGraphQL#345] opened 2024-02-23 07:43 UTC
I'm reposting a [question asked on Stackoverflow](https://stackoverflow.com/questions/78043723/use-outputcache-with-entity-graphql). I'm not sure if this is related to `EntityGraphQL.AspNet` or asp.net core/output caching itself.

---------------------------------------------

I'm trying to setup [output caching][1] using [Entity GraphQl][2], but can't get it to work. It's a net8.0 project with `EntityGraphQL.AspNet` 5.1.1.

Here's my reduced `Program.cs` 

```c#
using EntityGraphQL.AspNet;
using MedicalData.DataAccess;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddControllers();

builder.Services.AddOutputCache();

builder.Services.AddEndpointsApiExplorer();

builder.Services.AddSwaggerGen();

builder.Services.AddMedicalDataDataAccess(builder.Configuration.GetSection("MedicalDataDataAccess").Bind);
builder.Services.AddGraphQLSchema<MedicalDataDbContext>();

var app = builder.Build();

app.UseHttpsRedirection();

app.UseOutputCache();

app.MapGraphQL<MedicalDataDbContext>(
    configureEndpoint: endpointConventionBuilder =>
        endpointConventionBuilder.CacheOutput(outputCachePolicyBuilder =>
        {
            outputCachePolicyBuilder.VaryByValue(context =>
            {
                context.Request.EnableBuffering();

                using var bodyReader = new StreamReader(context.Request.Body, leaveOpen: true);
                var bodyContent = bodyReader.ReadToEndAsync()
                                            .Result
                                            .Replace(" ", "");

                // Reset the stream position to enable subsequent reads
                context.Request.Body.Position = 0;

                Console.WriteLine($"VaryByValue: {bodyContent}");

                return new KeyValuePair<string, string>("graphQl-requestBody", bodyContent);
            });

            outputCachePolicyBuilder.Expire(TimeSpan.FromHours(6));
        }));
app.MapGraphQLAltair();

app.MapControllers();

app.Run();
```

When executing the same graphql query multiple times, it is never being retrieved from the cache. The vary by value function is being executed each time, then the EF query:

    VaryByValue: {"query":"{\narticle(id:3){\nupdatedOn\ndescription{\ncurrent\n}\n}\n}","variables":{},"operationName":null}
    info: Microsoft.EntityFrameworkCore.Database.Command[20101]
          Executed DbCommand (1ms) [Parameters=[@__Value_id_Value_0='?' (DbType = Int64)], CommandType='Text', CommandTimeout='30']
          SELECT ...
    	  
    VaryByValue: {"query":"{\narticle(id:3){\nupdatedOn\ndescription{\ncurrent\n}\n}\n}","variables":{},"operationName":null}
    info: Microsoft.EntityFrameworkCore.Database.Command[20101]
          Executed DbCommand (1ms) [Parameters=[@__Value_id_Value_0='?' (DbType = Int64)], CommandType='Text', CommandTimeout='30']
          SELECT ...

I've added a log entry in a controller endpoint marked with `[OutputCache(Duration = 60 * 60)]`. If it is being called multiple times, only the first call enters, the subsequent ones come from the cache:

    GetPaged ArticleResultDtos
    info: Microsoft.EntityFrameworkCore.Database.Command[20101]
          Executed DbCommand (2ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
          SELECT COUNT(*)
          FROM [Articles] AS [a]
    info: Microsoft.EntityFrameworkCore.Database.Command[20101]
          Executed DbCommand (3ms) [Parameters=[@__p_0='?' (DbType = Int32), @__p_1='?' (DbType = Int32)], CommandType='Text', CommandTimeout='30']
          SELECT ...

When using Redis, instead of the in memory cache for output caching, there is no entry written for graphql, for the controller call, there is one.

What am I missing to make the GraphQl output cache work?

  [1]: https://learn.microsoft.com/en-us/aspnet/core/performance/caching/output?view=aspnetcore-8.0
  [2]: https://entitygraphql.github.io/

**Comment by lukemurray** [comment] 2024-02-24 01:56
Thanks for the report and steps to reproduce. I'll have to dig into it and take a look. There is some caching behaviour in the core library, but this should still work.

**Comment by PhilippeWaeber** [comment] 2024-02-26 12:57
Hi @lukemurray, thanks for having a look and for providing this library.
I think I've found the technical reason output caching doesn't work, but not why this property is being set or who sets is. 

In the `OutputCacheMiddleware`, which is part of the framework, the invocation is handled like this:

```c#
private async Task InvokeAwaited(HttpContext httpContext, IReadOnlyList<IOutputCachePolicy> policies)
{
	OutputCacheContext context = new OutputCacheContext
	{
		HttpContext = httpContext
	};
	AddOutputCacheFeature(context);
	bool hasException = false;
	bool executed;
	try
	{
		foreach (IOutputCachePolicy policy in policies)
		{
			await policy.CacheRequestAsync(context, httpContext.RequestAborted);
		}
		if (context.EnableOutputCaching)
		{
			if (context.AllowCacheLookup)
			{
				bool num = await TryServeFromCacheAsync(context, policies);
				context.ReleaseCachedResponse();
				if (num)
				{
					return;
				}
			}
			if (context.AllowCacheStorage)
			{
				CreateCacheKey(context);
				executed = false;
				if (context.AllowLocking)
				{
					OutputCacheEntry cacheEntry = await _requestDispatcher.ScheduleAsync(context.CacheKey, (string key) => ExecuteResponseAsync());
					if (executed || await TryServeCachedResponseAsync(context, cacheEntry, policies))
					{
						return;
					}
				}
				await ExecuteResponseAsync();
				return;
			}
		}
		await _next(httpContext);
	}
	catch
	{
		hasException = true;
		throw;
	}
	finally
	{
		if (!hasException)
		{
			context.ReleaseCachedResponse();
		}
		RemoveOutputCacheFeature(httpContext);
	}
	async Task<OutputCacheEntry> ExecuteResponseAsync()
	{
		ShimResponseStream(context);
		try
		{
			await _next(httpContext);
			foreach (IOutputCachePolicy policy2 in policies)
			{
				await policy2.ServeResponseAsync(context, httpContext.RequestAborted);
			}
			StartResponse(context);
			await FinalizeCacheBodyAsync(context);
			executed = true;
		}
		finally
		{
			UnshimResponseStream(context);
		}
		if (!context.AllowCacheStorage)
		{
			context.ReleaseCachedResponse();
		}
		return context.CachedResponse;
	}
}
```

For a graphql call, `context.AllowCacheLookup` is `false`, for the controller call, it is `true`. AFAICT this is the origin of my issue.

**Comment by lukemurray** [comment] 2024-02-26 23:57
Reading [this link](https://learn.microsoft.com/en-us/aspnet/core/performance/caching/output?view=aspnetcore-8.0#default-output-caching-policy) it looks like `POST` commands are not cached int he default policy. `app.MapGraphQL` sets the endpoint up as a `POST`.

This [section](https://learn.microsoft.com/en-us/aspnet/core/performance/caching/output?view=aspnetcore-8.0#override-the-default-policy) describes how to have a new policy that caches `POST` commands.

**Comment by PhilippeWaeber** [comment] 2024-02-27 12:20
Thanks! So completely unrelated to `EnityGraphQL`. When using a copy/paste of [section](https://learn.microsoft.com/en-us/aspnet/core/performance/caching/output?view=aspnetcore-8.0#override-the-default-policy), it works. Now I'd like to not have to override the entire behavior but only specify that a HTTP POST should also be allowed for caching. Let me figure out if a public class can be overridden.

Would you be interested in a documentation PR about this? I'd set one up once I'm happy with the entire implementation.

**Comment by lukemurray** [comment] 2024-02-28 00:35
Yes, a documentation PR would be welcomed. Thanks

**Comment by lukemurray** [comment] 2024-03-06 07:49
Closing this. Feel free to do a documentation PR. Thanks

**Closed by lukemurray** 2024-03-06 07:49 UTC
